spring:
  application:
    name: HeartCode
server:
  port: 8123
  servlet:
    context-path: /api
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.chp.heartcode.controller
knife4j:
  enable: true
  setting:
    language: zh-CN